export const ADMIN_SIGN_IN = 'ADMIN_SIGN_IN'
export const ADMIN_SIGN_IN_FAILURE = 'ADMIN_SIGN_IN_FAILURE'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'

export const SET_SESSION = 'SET_SESSION'
export const SESSION_CHECK_DONE = 'SESSION_CHECK_DONE'

export const GET_ALL_RESTAURANTS = 'GET_ALL_RESTAURANTS'
export const GET_ALL_RESTAURANTS_SUCCESS = 'GET_ALL_RESTAURANTS_SUCCESS'
export const GET_ALL_RESTAURANTS_FAILURE = 'GET_ALL_RESTAURANTS_FAILURE'

export const RESTAURANT_CHANGED = 'RESTAURANT_CHANGED'

export const ADD_RESTAURANT = 'ADD_RESTAURANT'
export const ADD_RESTAURANT_SUCCESS = 'ADD_RESTAURANT_SUCCESS'
export const ADD_RESTAURANT_FAILURE = 'ADD_RESTAURANT_FAILURE'

export const RESTAURANT_ADDED_UPDATED = 'RESTAURANT_ADDED_UPDATED'

export const GET_EXISTING_QRS = 'GET_EXISTING_QRS'
export const GET_EXISTING_QRS_SUCCESS = 'GET_EXISTING_QRS_SUCCESS'
export const GET_EXISTING_QRS_FAILURE = 'GET_EXISTING_QRS_FAILURE'

export const GENERATE_QRS = 'GENERATE_QRS'
export const GENERATE_QRS_SUCCESS = 'GENERATE_QRS_SUCCESS'
export const GENERATE_QRS_FAILURE = 'GENERATE_QRS_FAILURE'

export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const SET_TOAST = 'SET_TOAST'
export const RESET_TOAST = 'RESET_TOAST'
export const SET_TOAST_DISMISSING = 'SET_TOAST_DISMISSING'

export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'