export const ADMIN_SIGN_IN = 'ADMIN_SIGN_IN'
export const ADMIN_SIGN_IN_FAILURE = 'ADMIN_SIGN_IN_FAILURE'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE'

export const RESET_PASSWORD_LINK_STATUS = 'RESET_PASSWORD_LINK_STATUS'

export const CREATE_PASSWORD = 'CREATE_PASSWORD'
export const CREATE_PASSWORD_FAILURE = 'CREATE_PASSWORD_FAILURE'

export const SET_SESSION = 'SET_SESSION'
export const SESSION_CHECK_DONE = 'SESSION_CHECK_DONE'

export const GET_ALL_RESTAURANTS = 'GET_ALL_RESTAURANTS'
export const GET_ALL_RESTAURANTS_SUCCESS = 'GET_ALL_RESTAURANTS_SUCCESS'
export const GET_ALL_RESTAURANTS_FAILURE = 'GET_ALL_RESTAURANTS_FAILURE'

export const RESTAURANT_CHANGED = 'RESTAURANT_CHANGED'
export const SET_RESTAURANT = 'SET_RESTAURANT'
export const RESET_RESTAURANT = 'RESET_RESTAURANT'

export const ADD_RESTAURANT = 'ADD_RESTAURANT'
export const ADD_RESTAURANT_SUCCESS = 'ADD_RESTAURANT_SUCCESS'
export const ADD_RESTAURANT_FAILURE = 'ADD_RESTAURANT_FAILURE'

export const GET_RESTAURANT_TO_EDIT = 'GET_RESTAURANT_TO_EDIT'
export const GET_RESTAURANT_TO_EDIT_SUCCESS = 'GET_RESTAURANT_TO_EDIT_SUCCESS'
export const GET_RESTAURANT_TO_EDIT_FAILURE = 'GET_RESTAURANT_TO_EDIT_FAILURE'

export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT'
export const UPDATE_RESTAURANT_SUCCESS = 'UPDATE_RESTAURANT_SUCCESS'
export const UPDATE_RESTAURANT_FAILURE = 'UPDATE_RESTAURANT_FAILURE'

export const GET_EXISTING_QRS = 'GET_EXISTING_QRS'
export const GET_EXISTING_QRS_SUCCESS = 'GET_EXISTING_QRS_SUCCESS'
export const GET_EXISTING_QRS_FAILURE = 'GET_EXISTING_QRS_FAILURE'

export const GENERATE_QRS = 'GENERATE_QRS'
export const GENERATE_QRS_SUCCESS = 'GENERATE_QRS_SUCCESS'
export const GENERATE_QRS_FAILURE = 'GENERATE_QRS_FAILURE'

export const SET_TOAST = 'SET_TOAST'
export const RESET_TOAST = 'RESET_TOAST'
export const SET_TOAST_DISMISSING = 'SET_TOAST_DISMISSING'

export const SET_TABLE_NAME = 'SET_TABLE_NAME'
export const SET_TABLE_NAME_FAILURE = 'SET_TABLE_NAME_FAILURE'

export const GET_SUPER_ADMIN_DASHBOARD = 'GET_SUPER_ADMIN_DASHBOARD'
export const GET_SUPER_ADMIN_DASHBOARD_SUCCESS = 'GET_SUPER_ADMIN_DASHBOARD_SUCCESS'
export const GET_SUPER_ADMIN_DASHBOARD_FAILURE = 'GET_SUPER_ADMIN_DASHBOARD_FAILURE'

export const GET_RESTAURANT_DASHBOARD = 'GET_RESTAURANT_DASHBOARD'
export const GET_RESTAURANT_DASHBOARD_SUCCESS = 'GET_RESTAURANT_DASHBOARD_SUCCESS'
export const GET_RESTAURANT_DASHBOARD_FAILURE = 'GET_RESTAURANT_DASHBOARD_FAILURE'

export const GET_KITCHEN_DASHBOARD = 'GET_KITCHEN_DASHBOARD'
export const GET_KITCHEN_DASHBOARD_SUCCESS = 'GET_KITCHEN_DASHBOARD_SUCCESS'
export const GET_KITCHEN_DASHBOARD_FAILURE = 'GET_KITCHEN_DASHBOARD_FAILURE'

export const MARK_ITEM_READY = 'MARK_ITEM_READY'
export const MARK_ITEM_READY_FAILURE = 'MARK_ITEM_READY_FAILURE'

export const MARK_ORDER_READY = 'MARK_ORDER_READY'
export const MARK_ORDER_READY_FAILURE = 'MARK_ORDER_READY_FAILURE'

export const GET_TABLE_ORDERS = 'GET_TABLE_ORDERS'
export const GET_TABLE_ORDERS_SUCCESS = 'GET_TABLE_ORDERS_SUCCESS'
export const GET_TABLE_ORDERS_FAILURE = 'GET_TABLE_ORDERS_FAILURE'

export const CLEAR_TABLE_ORDERS = 'CLEAR_TABLE_ORDERS'

export const GET_ORDER_ITEM_DETAILS = 'GET_ORDER_ITEM_DETAILS'
export const GET_ORDER_ITEM_DETAILS_SUCCESS = 'GET_ORDER_ITEM_DETAILS_SUCCESS'
export const GET_ORDER_ITEM_DETAILS_FAILURE = 'GET_ORDER_ITEM_DETAILS_FAILURE'

export const CLEAR_ORDER_ITEM_DETAILS = 'CLEAR_ORDER_ITEM_DETAILS'

export const GET_ORDERS = 'GET_ORDERS'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE'

export const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS'
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS'
export const GET_ORDER_DETAILS_FAILURE = 'GET_ORDER_DETAILS_FAILURE'

export const CLEAR_ORDER_DETAILS = 'CLEAR_ORDER_DETAILS'

export const SUBMIT_NEW_ORDER = 'SUBMIT_NEW_ORDER'
export const SUBMIT_NEW_ORDER_SUCCESS = 'SUBMIT_NEW_ORDER_SUCCESS'
export const SUBMIT_NEW_ORDER_FAILURE = 'SUBMIT_NEW_ORDER_FAILURE'

export const ADD_ITEMS_TO_ORDER = 'ADD_ITEMS_TO_ORDER'
export const ADD_ITEMS_TO_ORDER_SUCCESS = 'ADD_ITEMS_TO_ORDER_SUCCESS'
export const ADD_ITEMS_TO_ORDER_FAILURE = 'ADD_ITEMS_TO_ORDER_FAILURE'

export const DELETE_ITEM = 'DELETE_ITEM'
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS'
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE'

export const DELETE_ITEM_SUCCESS_NO_MORE_DETAILS = 'DELETE_ITEM_SUCCESS_NO_MORE_DETAILS'

export const DELETE_ORDER = 'DELETE_ORDER'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE'

export const CLOSE_ORDER = 'CLOSE_ORDER'
export const CLOSE_ORDER_SUCCESS = 'CLOSE_ORDER_SUCCESS'
export const CLOSE_ORDER_FAILURE = 'CLOSE_ORDER_FAILURE'

export const MERGE_TABLES = 'MERGE_TABLES'
export const MERGE_TABLES_FAILURE = 'MERGE_TABLES_FAILURE'

export const UN_MERGE_TABLES = 'UN_MERGE_TABLES'
export const UN_MERGE_TABLES_FAILURE = 'UN_MERGE_TABLES_FAILURE'

export const GET_SERVICES_QUE = 'GET_SERVICES_QUE'
export const GET_SERVICES_QUE_SUCCESS = 'GET_SERVICES_QUE_SUCCESS'
export const GET_SERVICES_QUE_FAILURE = 'GET_SERVICES_QUE_FAILURE'

export const GET_STAFF_ASSIGNED_TABLES = 'GET_STAFF_ASSIGNED_TABLES'
export const GET_STAFF_ASSIGNED_TABLES_SUCCESS = 'GET_STAFF_ASSIGNED_TABLES_SUCCESS'
export const GET_STAFF_ASSIGNED_TABLES_FAILURE = 'GET_STAFF_ASSIGNED_TABLES_FAILURE'

export const ASSIGN_TABLES_TO_STAFF = 'ASSIGN_TABLES_TO_STAFF'
export const ASSIGN_TABLES_TO_STAFF_FAILURE = 'ASSIGN_TABLES_TO_STAFF_FAILURE'

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'

export const ADD_CATEGORY = 'ADD_CATEGORY'
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE'

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const UPDATE_CATEGORY_FAILURE = 'UPDATE_CATEGORY_FAILURE'

export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE'

export const GET_MENU = 'GET_MENU'
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS'
export const GET_MENU_FAILURE = 'GET_MENU_FAILURE'

export const ADD_MENU = 'ADD_MENU'
export const ADD_MENU_SUCCESS = 'ADD_MENU_SUCCESS'
export const ADD_MENU_FAILURE = 'ADD_MENU_FAILURE'

export const UPDATE_MENU = 'UPDATE_MENU'
export const UPDATE_MENU_SUCCESS = 'UPDATE_MENU_SUCCESS'
export const UPDATE_MENU_FAILURE = 'UPDATE_MENU_FAILURE'

export const ADD_ADDON = 'ADD_ADDON'
export const ADD_ADDON_SUCCESS = 'ADD_ADDON_SUCCESS'
export const ADD_ADDON_FAILURE = 'ADD_ADDON_FAILURE'

export const UPDATE_ADDON = 'UPDATE_ADDON'
export const UPDATE_ADDON_SUCCESS = 'UPDATE_ADDON_SUCCESS'
export const UPDATE_ADDON_FAILURE = 'UPDATE_ADDON_FAILURE'

export const GET_USERS = 'GET_USERS'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

export const ADD_USER = 'ADD_USER'
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'

export const UPLOAD_TO_S3 = 'UPLOAD_TO_S3'
export const UPLOAD_TO_S3_SUCCESS = 'UPLOAD_TO_S3_SUCCESS'
export const UPLOAD_TO_S3_FAILURE = 'UPLOAD_TO_S3_FAILURE'

export const DELETE_FROM_S3 = 'DELETE_FROM_S3'
export const DELETE_FROM_S3_SUCCESS = 'DELETE_FROM_S3_SUCCESS'
export const DELETE_FROM_S3_FAILURE = 'DELETE_FROM_S3_FAILURE'