export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'

export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const SET_SESSION = 'SET_SESSION'
export const SESSION_CHECK_DONE = 'SESSION_CHECK_DONE'
export const LOGOUT = 'LOGOUT'

export const SET_TOAST = 'SET_TOAST'
export const RESET_TOAST = 'RESET_TOAST'
export const SET_TOAST_DISMISSING = 'SET_TOAST_DISMISSING'

export const GET_ALL_RESTAURANTS = 'GET_ALL_RESTAURANTS'
export const GET_ALL_RESTAURANTS_SUCCESS = 'GET_ALL_RESTAURANTS_SUCCESS'
export const GET_ALL_RESTAURANTS_FAILURE = 'GET_ALL_RESTAURANTS_FAILURE'

export const GET_MENU = 'GET_MENU'
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS'
export const GET_MENU_FAILURE = 'GET_MENU_FAILURE'