export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'

export const REGISTER_RESTURENT = 'REGISTER_RESTURENT'
export const REGISTER_RESTURENT_SUCESS = 'REGISTER_RESTURENT_SUCESS'

export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const GET_RPOFILE = 'GET_RPOFILE'
export const GET_RPOFILE_SUCCESS = 'GET_RPOFILE_SUCCESS'
export const GET_RPOFILE_FAILURE = 'GET_RPOFILE_FAILURE'

export const UPDATE_RPOFILE = 'UPDATE_RPOFILE'
export const UPDATE_RPOFILE_SUCCESS = 'UPDATE_RPOFILE_SUCCESS'
export const UPDATE_RPOFILE_FAILURE = 'UPDATE_RPOFILE_FAILURE'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE'

export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD'
export const SET_NEW_PASSWORD_SUCCESS = 'SET_NEW_PASSWORD_SUCCESS'
export const SET_NEW_PASSWORD_FAILURE = 'SET_NEW_PASSWORD_FAILURE'



export const SET_SESSION = 'SET_SESSION'
export const SESSION_CHECK_DONE = 'SESSION_CHECK_DONE'
export const LOGOUT = 'LOGOUT'
export const SIGN_UP_SUCESS = 'SIGN_UP_SUCESS'

export const SET_TOAST = 'SET_TOAST'
export const RESET_TOAST = 'RESET_TOAST'
export const SET_TOAST_DISMISSING = 'SET_TOAST_DISMISSING'

export const GET_ALL_RESTAURANTS = 'GET_ALL_RESTAURANTS'
export const GET_ALL_RESTAURANTS_SUCCESS = 'GET_ALL_RESTAURANTS_SUCCESS'
export const GET_ALL_RESTAURANTS_FAILURE = 'GET_ALL_RESTAURANTS_FAILURE'

export const GET_ALL_ORDERS = 'GET_ALL_ORDERS'
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS'
export const GET_ALL_ORDERS_FAILURE = 'GET_ALL_ORDERS_FAILURE'

export const SEARCH_RESTURANT = 'SEARCH_RESTURANT'
export const SEARCH_RESTURANT_SUCCESS = 'SEARCH_RESTURANT_SUCCESS'
export const SEARCH_RESTURANT_FAILURE = 'SEARCH_RESTURANT_FAILURE'

export const GET_STATUS = 'GET_STATUS'
export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS'
export const GET_STATUS_FAILURE = 'GET_STATUS_FAILURE'

export const GET_MENU = 'GET_MENU'
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS'
export const GET_MENU_FAILURE = 'GET_MENU_FAILURE'

export const CALL_FOR_SERVICE = 'CALL_FOR_SERVICE'
export const CALL_FOR_SERVICE_SUCCESS = 'CALL_FOR_SERVICE_SUCCESS'
export const CALL_FOR_SERVICE_FAILURE = 'CALL_FOR_SERVICE_FAILURE'

export const DONOTDISTURB = 'DONOTDISTURB'
export const DONOTDISTURB_SUCCESS = 'DONOTDISTURB_SUCCESS'
export const DONOTDISTURB_FAILURE = 'DONOTDISTURB_FAILURE'

export const GET_RESTAURANT_DETAILS = 'GET_RESTAURANT_DETAILS'
export const GET_RESTAURANT_DETAILS_SUCCESS = 'GET_RESTAURANT_DETAILS_SUCCESS'
export const GET_RESTAURANT_DETAILS_FAILURE = 'GET_RESTAURANT_DETAILS_FAILURE'

export const CLOSE_ORDER = 'CLOSE_ORDER'
export const CLOSE_ORDER_SUCCESS = 'CLOSE_ORDER_SUCCESS'
export const CLOSE_ORDER_FAILURE = 'CLOSE_ORDER_FAILURE'

export const GET_ORDER_ITEMS = 'GET_ORDER_ITEMS'
export const GET_ORDER_ITEMS_SUCCESS = 'GET_ORDER_ITEMS_SUCCESS'
export const GET_ORDER_ITEMS_FAILURE = 'GET_ORDER_ITEMS_FAILURE'

export const GET_TAKE_ORDER_ITEMS = 'GET_TAKE_ORDER_ITEMS'
export const GET_TAKE_ORDER_ITEMS_SUCCESS = 'GET_TAKE_ORDER_ITEMS_SUCCESS'
export const GET_TAKE_ORDER_ITEMS_FAILURE = 'GET_TAKE_ORDER_ITEMS_FAILURE'

export const INITIALIZE_ORDER = 'INITIALIZE_ORDER'
export const SET_ORDER = 'SET_ORDER'
export const INITIALIZE_ORDER_FAILURE = 'INITIALIZE_ORDER_FAILURE'
export const ORDER_CHECK_DONE = 'ORDER_CHECK_DONE'
export const EDIT_ORDER_ITEM = 'EDIT_ORDER_ITEM'
export const SET_ORDER_ITEM = 'SET_ORDER_ITEM'
export const DELETE_ORDER_ITEM = 'DELETE_ORDER_ITEM'
export const DELETE_ALL_ORDER_ITEM = 'DELETE_ALL_ORDER_ITEM'

export const GET_ORDER_DETAIL = 'GET_ORDER_DETAIL'
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS'
export const GET_ORDER_DETAIL_FAILURE = 'GET_ORDER_DETAIL_FAILURE'

export const SET_ORDER_ITEM_SUCCESS = 'SET_ORDER_ITEM_SUCCESS'
export const SET_TAKE_ORDER_ITEM_SUCCESS = 'SET_TAKE_ORDER_ITEM_SUCCESS'
export const SET_ORDER_ITEM_FAILED = 'SET_ORDER_ITEM_FAILED'


export const SUBMIT_ORDER_ITEM = 'SUBMIT_ORDER_ITEM'
export const SUBMIT_ORDER_ITEM_FAILED = 'SUBMIT_ORDER_ITEM_FAILED'

export const TAKIE_AWAY_ORDER = 'TAKIE_AWAY_ORDER'
export const TAKIE_AWAY_ORDER_FAILED = 'TAKIE_AWAY_ORDER_FAILED'

export const ALREADY_IN_CART = 'ALREADY_IN_CART'
export const CANT_SIGN_OUT = 'CANT_SIGN_OUT'
export const CANT_PAY = 'CANT_PAY'